version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: univille
       MYSQL_DATABASE: colabassistant
       MYSQL_USER: bob
       MYSQL_PASSWORD: bob
   colab:
     depends_on:
       - db
     image: colabassistantdockerimage:latest
     volumes:
       - colabimages:/var/colabimages
     ports:
       - "80:80"
     restart: always
     environment:
       DATABASE_URL: jdbc:mysql://db:3306/colabassistant?reconnect=true&user=bob&password=bob
volumes:
    dbdata:
    colabimages:
